"""Export/router for generating downloadable reports."""

import csv
import io
import json
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse, Response
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from sqlalchemy.orm import selectinload

from app.database import get_db
from app.models import Comparison, Conversation, QuickTestLog

router = APIRouter(prefix="/api/exports", tags=["exports"])


def _html_boilerplate(title: str, body: str) -> str:
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>{title}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #141414; color: #d4d4d4; padding: 2rem; max-width: 1200px; margin: auto; }}
  h1 {{ color: #c9673a; }}
  h2 {{ color: #c4983a; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ text-align: left; padding: 0.6rem; border-bottom: 1px solid #333; }}
  th {{ color: #888; text-transform: uppercase; font-size: 0.75rem; }}
  .card {{ background: #1e1e1e; border: 1px solid #333; border-radius: 6px; padding: 1rem; margin: 1rem 0; }}
  .label {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }}
  .high {{ background: #3a1a1a; color: #c94a4a; }}
  .medium {{ background: #3a2a1a; color: #c4983a; }}
  .low {{ background: #1a2a1a; color: #4a9a6a; }}
  .pre {{ white-space: pre-wrap; font-family: monospace; font-size: 0.85rem; }}
</style></head><body>{body}</body></html>"""


def _score_css(s: float) -> str:
    if s >= 80:
        return "high"
    if s >= 50:
        return "medium"
    return "low"


# ── Comparison Export ─────────────────────────────────────────────────────

def _comparison_html(c: Comparison) -> str:
    rows = ""
    for r in c.results:
        rows += f"""<div class="card">
  <h3>{r.target_name} <span style="color:#555;font-weight:normal;font-size:0.85rem">({r.model})</span></h3>
  <div class="pre">{r.response}</div>
  <p style="margin-top:0.5rem">
    <span class="label {_score_css(r.score)}">{r.label} — {r.score}/100</span>
    <span style="color:#555;font-size:0.8rem;margin-left:1rem">
      Refusal: {r.refusal_signals} · Compliance: {r.compliance_signals} · {r.response_time_ms}ms
    </span>
  </p>
  {f'<p style="color:#c94a4a;font-size:0.85rem">{r.details}</p>' if r.details else ''}
</div>"""
    return _html_boilerplate(
        f"Comparison #{c.id}",
        f"<h1>Side-by-Side Comparison #{c.id}</h1>"
        f'<p style="color:#888">Prompt: <span style="color:#d4d4d4">{c.prompt}</span></p>'
        f'<p style="color:#555">{c.results[0].target_name if c.results else ""} and others · {len(c.results)} targets</p>'
        f"{rows}"
        f'<p style="color:#555;font-size:0.75rem;margin-top:2rem">Generated by REDFIRE · {c.created_at.strftime("%Y-%m-%d %H:%M UTC")}</p>'
    )


def _comparison_csv(c: Comparison) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["target_id", "target_name", "model", "response", "score", "label",
                 "refusal_signals", "compliance_signals", "response_time_ms", "details", "error"])
    for r in c.results:
        w.writerow([r.target_id, r.target_name, r.model, r.response, r.score, r.label,
                     r.refusal_signals, r.compliance_signals, r.response_time_ms, r.details, r.error])
    return buf.getvalue()


@router.get("/comparisons/{comparison_id}")
async def export_comparison(
    comparison_id: int,
    format: str = "html",
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Comparison).options(selectinload(Comparison.results)).where(Comparison.id == comparison_id)
    )
    c = result.scalar_one_or_none()
    if not c:
        raise HTTPException(404, "Comparison not found")

    if format not in ("html", "csv", "json"):
        raise HTTPException(400, "format must be html, csv, or json")
    if format == "json":
        data = {
            "id": c.id,
            "prompt": c.prompt,
            "created_at": c.created_at.isoformat(),
            "results": [
                {
                    "target_id": r.target_id,
                    "target_name": r.target_name,
                    "model": r.model,
                    "response": r.response,
                    "score": r.score,
                    "label": r.label,
                    "refusal_signals": r.refusal_signals,
                    "compliance_signals": r.compliance_signals,
                    "response_time_ms": r.response_time_ms,
                    "details": r.details,
                    "error": r.error,
                }
                for r in c.results
            ],
        }
        return Response(json.dumps(data, indent=2), media_type="application/json",
                        headers={"Content-Disposition": f'attachment; filename="comparison_{c.id}.json"'})
    if format == "csv":
        return PlainTextResponse(_comparison_csv(c), media_type="text/csv",
                                 headers={"Content-Disposition": f'attachment; filename="comparison_{c.id}.csv"'})
    return Response(_comparison_html(c), media_type="text/html",
                    headers={"Content-Disposition": f'attachment; filename="comparison_{c.id}.html"'})


# ── Conversation Export ───────────────────────────────────────────────────

@router.get("/conversations/{conversation_id}")
async def export_conversation(
    conversation_id: int,
    format: str = "html",
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Conversation).options(selectinload(Conversation.turns)).where(Conversation.id == conversation_id)
    )
    conv = result.scalar_one_or_none()
    if not conv:
        raise HTTPException(404, "Conversation not found")

    if format not in ("html", "json"):
        raise HTTPException(400, "format must be html or json")
    if format == "json":
        data = {
            "id": conv.id,
            "name": conv.name,
            "created_at": conv.created_at.isoformat(),
            "turns": [
                {"role": t.role, "content": t.content, "score": t.score, "label": t.label}
                for t in conv.turns
            ],
        }
        return Response(json.dumps(data, indent=2), media_type="application/json",
                        headers={"Content-Disposition": f'attachment; filename="conversation_{conv.id}.json"'})

    turns_html = ""
    for t in conv.turns:
        side = "right" if t.role == "user" else "left"
        bg = "#2a1a1a" if t.role == "user" else "#1e1e1e"
        align = "right" if t.role == "user" else "left"
        turns_html += f"""<div style="display:flex;justify-content:{align};margin:0.5rem 0">
  <div style="background:{bg};border:1px solid #333;border-radius:6px;padding:0.8rem;max-width:80%">
    <p style="color:#888;font-size:0.75rem;margin:0 0 0.3rem">{'You' if t.role == 'user' else 'Model'}</p>
    <div class="pre" style="margin:0">{t.content}</div>
    {f'<p style="margin:0.3rem 0 0;font-size:0.75rem"><span class="label {_score_css(t.score)}">{t.label} — {t.score}/100</span></p>' if t.role == 'assistant' and t.label else ''}
  </div>
</div>"""
    body = f"<h1>{conv.name or f'Conversation #{conv.id}'}</h1>{turns_html}"
    return Response(_html_boilerplate(conv.name or f"Conversation #{conv.id}", body), media_type="text/html",
                    headers={"Content-Disposition": f'attachment; filename="conversation_{conv.id}.html"'})


# ── Quick Test Logs Export ────────────────────────────────────────────────

@router.get("/quick-test-logs")
async def export_quick_test_logs(
    format: str = "csv",
    limit: int = 500,
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(select(QuickTestLog).order_by(QuickTestLog.created_at.desc()).limit(limit))
    logs = result.scalars().all()

    if format not in ("csv", "json"):
        raise HTTPException(400, "format must be csv or json")
    if format == "json":
        data = [
            {
                "id": log.id,
                "target_id": log.target_id,
                "target_name": log.target_name,
                "model": log.model,
                "prompt": log.prompt,
                "response": log.response,
                "score": log.score,
                "label": log.label,
                "refusal_signals": log.refusal_signals,
                "compliance_signals": log.compliance_signals,
                "details": log.details,
                "created_at": log.created_at.isoformat(),
            }
            for log in logs
        ]
        return Response(json.dumps(data, indent=2), media_type="application/json",
                        headers={"Content-Disposition": 'attachment; filename="quick_test_logs.json"'})

    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["id", "target_id", "target_name", "model", "prompt", "response", "score", "label",
                 "refusal_signals", "compliance_signals", "details", "created_at"])
    for log in logs:
        w.writerow([log.id, log.target_id, log.target_name, log.model, log.prompt, log.response,
                     log.score, log.label, log.refusal_signals, log.compliance_signals, log.details,
                     log.created_at.isoformat()])
    return PlainTextResponse(buf.getvalue(), media_type="text/csv",
                             headers={"Content-Disposition": 'attachment; filename="quick_test_logs.csv"'})
